"""
sentinel.pilot.fixes
~~~~~~~~~~~~~~~~~~~~
Library-level "fix" actions referenced by ``sentinel audit-gap``.

Each fix closes exactly one gap. They are small, idempotent, and
never phone home. Running them updates the pilot config so the next
``sentinel audit-gap`` run reflects the change.

Two fixes ship in v3.2.0:

- :func:`fix_kill_switch`   — registers a kill switch handler stub.
- :func:`fix_retention`     — records a retention policy in days.

More fixes can be added later without churning the CLI dispatch
table — each one is a small function returning a
:class:`FixResult`.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from datetime import UTC, datetime
from pathlib import Path

from sentinel.pilot.config import (
    KillSwitchConfig,
    PilotConfig,
    RetentionConfig,
    default_pilot_paths,
    load_pilot_config,
    save_pilot_config,
)

KILL_SWITCH_HANDLER_FILENAME = "kill_switch.py"

KILL_SWITCH_HANDLER_SOURCE = '''"""
kill_switch.py
~~~~~~~~~~~~~~
Generated by `sentinel fix kill-switch`.

This file is a minimal Art. 14 (human oversight) halt handler. Wire
the `engage()` and `disengage()` functions to whatever your operator
team uses — a webhook, a physical button, an ops console. The
handler keeps the library-layer contract simple: it just tells the
running Sentinel instance to stop approving decisions.

Do NOT remove this file unless you replace the registration in
./.sentinel/config.json accordingly.
"""

from sentinel import Sentinel


def engage(sentinel: Sentinel, reason: str) -> None:
    """Halt all traced calls until disengage() is called."""
    sentinel.engage_kill_switch(reason)


def disengage(sentinel: Sentinel, reason: str) -> None:
    """Resume traced calls. The reason is required for auditability."""
    sentinel.disengage_kill_switch(reason)
'''


@dataclass(frozen=True)
class FixResult:
    """Structured output of a fix, for CLI rendering and tests."""

    fix_id: str  # "kill_switch" | "retention"
    succeeded: bool
    points_delta: int  # audit-gap points closed (best estimate)
    detail: str
    artefact_path: Path | None = None
    config_path: Path | None = None


def _load_or_init_config(config_path: Path) -> PilotConfig:
    cfg = load_pilot_config(config_path)
    if cfg is not None:
        return cfg
    # No config yet — create one with safe defaults. This keeps
    # `sentinel fix ...` usable even if the user never ran quickstart.
    return PilotConfig(
        project="sentinel-pilot",
        storage_path="./.sentinel/traces.db",
        data_residency="EU_DE",
        sovereign_scope="EU",
    )


def fix_kill_switch(base: Path | str | None = None) -> FixResult:
    """
    Register a kill switch handler for Art. 14 human oversight.

    Writes a stub handler at ``./.sentinel/kill_switch.py`` and marks
    the kill switch as registered in the pilot config. Idempotent —
    running twice is safe and returns ``succeeded=True`` both times.
    """
    pilot_dir, config_path, _ = default_pilot_paths(base)
    pilot_dir.mkdir(parents=True, exist_ok=True)
    handler_path = pilot_dir / KILL_SWITCH_HANDLER_FILENAME

    if not handler_path.exists():
        handler_path.write_text(KILL_SWITCH_HANDLER_SOURCE, encoding="utf-8")
        points = 10
        detail = "kill switch handler registered"
    else:
        points = 0
        detail = "kill switch already registered (no change)"

    cfg = _load_or_init_config(config_path)
    was_registered = cfg.kill_switch.registered
    new_cfg = replace(
        cfg,
        kill_switch=KillSwitchConfig(
            registered=True,
            handler_path=str(handler_path),
            last_tested_at=datetime.now(UTC).isoformat(timespec="seconds"),
        ),
    )
    save_pilot_config(new_cfg, config_path)

    if not was_registered:
        points = 10  # always award when transitioning from unregistered

    return FixResult(
        fix_id="kill_switch",
        succeeded=True,
        points_delta=points,
        detail=detail,
        artefact_path=handler_path,
        config_path=config_path,
    )


def fix_retention(
    days: int,
    base: Path | str | None = None,
) -> FixResult:
    """
    Record a retention policy for the evidence record.

    The default recommendation is 2555 days (~7 years), which exceeds
    both the Annex III record-keeping window and typical national
    auditor requirements. Callers may pass any positive integer.
    """
    if days <= 0:
        return FixResult(
            fix_id="retention",
            succeeded=False,
            points_delta=0,
            detail=f"retention days must be > 0 (got {days})",
        )

    pilot_dir, config_path, _ = default_pilot_paths(base)
    pilot_dir.mkdir(parents=True, exist_ok=True)

    cfg = _load_or_init_config(config_path)
    was_configured = cfg.retention.days is not None
    new_cfg = replace(
        cfg,
        retention=RetentionConfig(days=days, policy_name="default"),
    )
    save_pilot_config(new_cfg, config_path)

    points = 0 if was_configured else 10
    detail = (
        f"retention policy set to {days} days"
        if not was_configured
        else f"retention policy updated to {days} days"
    )

    return FixResult(
        fix_id="retention",
        succeeded=True,
        points_delta=points,
        detail=detail,
        artefact_path=None,
        config_path=config_path,
    )
