"""
sentinel.pilot.quickstart
~~~~~~~~~~~~~~~~~~~~~~~~~
Generates the first-run scaffold for new users.

The quickstart command creates three things and nothing else:

1. ``./.sentinel/`` directory (pilot state lives here)
2. ``./.sentinel/config.json`` (PilotConfig with defaults)
3. ``./hello_sentinel.py`` — a 12-line, zero-dependency example

It is **idempotent**: re-running it without ``--force`` prints what
already exists and leaves the filesystem untouched. With ``--force``
it overwrites the example file but preserves the config to avoid
erasing user progress on the audit-gap score.

The example file deliberately wraps a **plain Python function**, not
an LLM or LangChain call. This removes the need for API keys,
network, model provider choice, or extra dependencies — the golden
path stays golden.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from sentinel.pilot.config import (
    DEFAULT_DB_FILENAME,
    DEFAULT_PILOT_DIR,
    PilotConfig,
    default_pilot_paths,
    load_pilot_config,
    save_pilot_config,
)

EXAMPLE_FILENAME = "hello_sentinel.py"

EXAMPLE_SOURCE = '''"""
hello_sentinel.py
~~~~~~~~~~~~~~~~~
Generated by `sentinel quickstart`.

Wrap any function that makes a decision with @sentinel.trace.
Every call produces an immutable, EU AI Act Art. 12-conformant
trace record stored locally at ./.sentinel/traces.db — no
network, no cloud account, no API key.
"""

from sentinel import Sentinel, DataResidency
from sentinel.storage import SQLiteStorage

sentinel = Sentinel(
    storage=SQLiteStorage("./.sentinel/traces.db"),
    project="sentinel-pilot",
    data_residency=DataResidency.EU_DE,
    sovereign_scope="EU",
)


@sentinel.trace
def approve_expense(amount: float, category: str) -> dict:
    if amount > 1000:
        return {"decision": "deny", "reason": "over_limit"}
    return {"decision": "approve", "amount": amount}


if __name__ == "__main__":
    sample = [120, 450, 800, 1500, 2400, 90, 310, 1100, 770, 250]
    for amount in sample:
        approve_expense(amount=amount, category="travel")
    print(f"sentinel: {len(sample)} decisions traced")
    print("         next: sentinel evidence-pack --output audit.pdf")
'''


@dataclass(frozen=True)
class QuickstartResult:
    """Structured output of a quickstart run, for CLI rendering and tests."""

    pilot_dir: Path
    config_path: Path
    db_path: Path
    example_path: Path
    config_was_created: bool
    example_was_created: bool
    example_was_overwritten: bool
    already_initialized: bool


def run_quickstart(
    base: Path | str | None = None,
    *,
    force: bool = False,
) -> QuickstartResult:
    """
    Initialise a Sentinel pilot in ``base`` (default: cwd).

    Safe to call multiple times. Returns a :class:`QuickstartResult`
    describing what was created or skipped so the CLI can render an
    accurate summary.
    """
    pilot_dir, config_path, db_path = default_pilot_paths(base)
    base_path = Path(base) if base is not None else Path.cwd()
    example_path = (base_path / EXAMPLE_FILENAME).resolve()

    pilot_dir.mkdir(parents=True, exist_ok=True)

    existing_config = load_pilot_config(config_path)
    config_was_created = False
    if existing_config is None:
        storage_rel = f"./{DEFAULT_PILOT_DIR}/{DEFAULT_DB_FILENAME}"
        new_config = PilotConfig(
            project="sentinel-pilot",
            storage_path=storage_rel,
            data_residency="EU_DE",
            sovereign_scope="EU",
        )
        save_pilot_config(new_config, config_path)
        config_was_created = True

    example_existed = example_path.exists()
    example_was_created = False
    example_was_overwritten = False
    if not example_existed:
        example_path.write_text(EXAMPLE_SOURCE, encoding="utf-8")
        example_was_created = True
    elif force:
        example_path.write_text(EXAMPLE_SOURCE, encoding="utf-8")
        example_was_overwritten = True

    already_initialized = (
        existing_config is not None and example_existed and not force
    )

    return QuickstartResult(
        pilot_dir=pilot_dir,
        config_path=config_path,
        db_path=db_path,
        example_path=example_path,
        config_was_created=config_was_created,
        example_was_created=example_was_created,
        example_was_overwritten=example_was_overwritten,
        already_initialized=already_initialized,
    )
